#!/usr/bin/env node
// Turns upstream's UI catalogs (reference/harbor/src/lib/i18n/locales/<lang>.ts) into the
// files the tvOS app bundles, so the Swift UI and the engine translate with upstream's copy:
//
//   App/Locales/<lang>.lproj/Localizable.strings     every upstream key, verbatim, plus the
//                                                    Swift-format twins of {placeholder} keys
//   App/Locales/<lang>.lproj/Localizable.stringsdict plural forms of one-placeholder keys
//   App/Locales/<lang>.json                          the raw catalog, handed to the engine's
//                                                    lib/i18n (i18n.installCatalog) at boot
//
// tools/locales-tvos.json adds the TV's own copy that upstream has no key for (Apple TV phone
// sheets, relay/list/guide notes …): { "English {placeholder} key": { "<lang>": "…" } }, keys
// starting with "_" are comments. Upstream keys always win; {placeholder} keys get the same
// Swift-format twins as upstream's. Swift only, the engine never sees them.
//
// Keys are upstream's English source strings (translate.ts). SwiftUI's Text("\(n) results")
// looks up "%lld results", so a key like "{count} results" also gets "%lld results" and
// "%@ results" entries whose values use positional specifiers (%1$lld) in the translation's
// order. The engine bundle stubs load-locale on purpose (20 MB of TS); this is where the
// catalogs go instead. Output is gitignored; CI runs this in the "Build engine bundle" step.
//
//   node tools/build_locales.mjs
import { createRequire } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";
import fs from "node:fs";
import os from "node:os";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const i18nDir = path.join(root, "reference/harbor/src/lib/i18n");
const outDir = path.join(root, "App/Locales");
const require = createRequire(path.join(root, "engine/package.json"));
const { build } = require("esbuild");

// languages.ts, read through the same bundler so the list tracks upstream.
async function loadModule(entry) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "harbor-locales-"));
  const outfile = path.join(tmp, "m.mjs");
  await build({ entryPoints: [entry], bundle: true, format: "esm", platform: "node", outfile, logLevel: "error", charset: "utf8" });
  try {
    return await import(pathToFileURL(outfile).href);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

const { LANGUAGES } = await loadModule(path.join(i18nDir, "languages.ts"));
const en = (await loadModule(path.join(i18nDir, "locales/en.ts"))).default;

const VARIANT = /#(one|few|many)$/;
const extras = JSON.parse(fs.readFileSync(path.join(root, "tools/locales-tvos.json"), "utf8"));
for (const k of Object.keys(extras)) if (k.startsWith("_")) delete extras[k];
const PLACEHOLDER = /\{([A-Za-z0-9_]+)\}/g;

/** .strings escaping: backslash, quote and control characters; everything else stays UTF-8. */
const esc = (s) =>
  s.replace(/[\\"\n\r\t]/g, (c) => ({ "\\": "\\\\", '"': '\\"', "\n": "\\n", "\r": "\\r", "\t": "\\t" })[c])
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g, (c) => `\\U${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
const xml = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/**
 * "{a} of {b}" → every Swift spelling of its placeholders (each one %@ or %lld) paired with the
 * translation rewritten to positional specifiers. Literal % doubles, as LocalizedStringKey does.
 * Returns [] when the translation names a placeholder the key does not have.
 */
function swiftForms(key, value) {
  const names = [...key.matchAll(PLACEHOLDER)].map((m) => m[1]);
  if (!names.length || names.length > 3) return [];
  const pos = new Map();
  names.forEach((n, i) => { if (!pos.has(n)) pos.set(n, i + 1); });
  for (const m of value.matchAll(PLACEHOLDER)) if (!pos.has(m[1])) return [];
  const out = [];
  for (let mask = 0; mask < 1 << names.length; mask++) {
    const spec = names.map((_, i) => (mask >> i) & 1 ? "lld" : "@");
    let i = 0;
    const k = key.replace(/%/g, "%%").replace(PLACEHOLDER, () => `%${spec[i++]}`);
    // A repeated placeholder takes the first occurrence's argument and type.
    const v = value.replace(/%/g, "%%").replace(PLACEHOLDER, (_, n) => `%${pos.get(n)}$${spec[pos.get(n) - 1]}`);
    out.push([k, v]);
  }
  return out;
}

function stringsFile(entries) {
  const lines = ["/* Generated by tools/build_locales.mjs from reference/harbor/src/lib/i18n. Do not edit. */"];
  for (const [k, v] of entries) lines.push(`"${esc(k)}" = "${esc(v)}";`);
  return lines.join("\n") + "\n";
}

/** Plural keys with one placeholder → .stringsdict, CLDR categories mapped onto upstream's forms. */
function stringsdictFile(plurals) {
  const body = [];
  const seen = new Set();
  for (const { key, forms } of plurals) {
    // "{n} wins" and "{count} wins" are one Swift key; the first (upstream's order) wins.
    const [[swiftKey]] = swiftForms(key, key).filter(([k]) => k.includes("%lld"));
    if (seen.has(swiftKey)) continue;
    seen.add(swiftKey);
    const variant = (v) => v.replace(/%/g, "%%").replace(PLACEHOLDER, "%lld");
    // translate.ts PLURAL_RULES only knows one / few / many (the base key); "two" is ar's 2,
    // which upstream files under few; zero, many and other are all upstream's base form.
    const cats = { zero: forms.many, one: forms.one ?? forms.many, two: forms.few ?? forms.many, few: forms.few ?? forms.many, many: forms.many, other: forms.many };
    body.push(`\t<key>${xml(swiftKey)}</key>`, "\t<dict>", "\t\t<key>NSStringLocalizedFormatKey</key>", "\t\t<string>%#@n@</string>", "\t\t<key>n</key>", "\t\t<dict>",
      "\t\t\t<key>NSStringFormatSpecTypeKey</key>", "\t\t\t<string>NSStringPluralRuleType</string>", "\t\t\t<key>NSStringFormatValueTypeKey</key>", "\t\t\t<string>lld</string>");
    for (const [cat, v] of Object.entries(cats)) body.push(`\t\t\t<key>${cat}</key>`, `\t\t\t<string>${xml(variant(v))}</string>`);
    body.push("\t\t</dict>", "\t</dict>");
  }
  return ['<?xml version="1.0" encoding="UTF-8"?>', '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">', "<dict>", ...body, "</dict>", "</plist>", ""].join("\n");
}

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

// en: only the id-style keys (nav.home = Home); every other English string is its own key.
{
  const ids = Object.entries(en).filter(([k, v]) => k !== v && !VARIANT.test(k) && !k.includes(" ") && /^[a-z][\w-]*(\.[\w-]+)+$/.test(k));
  fs.mkdirSync(path.join(outDir, "en.lproj"));
  fs.writeFileSync(path.join(outDir, "en.lproj/Localizable.strings"), stringsFile(ids));
}

let total = 0;
const summary = [];
for (const { code } of LANGUAGES) {
  if (code === "en") continue;
  const catalog = (await loadModule(path.join(i18nDir, `locales/${code}.ts`))).default;
  const entries = new Map();
  const put = (k, v) => { if (!entries.has(k)) entries.set(k, v); };
  // 1. upstream keys verbatim (the engine's table, and every placeholder-free Swift literal).
  for (const [k, v] of Object.entries(catalog)) if (typeof v === "string" && !VARIANT.test(k)) put(k, v);
  // 2. id-style keys (nav.home) are shown in English by their en value ("Home").
  for (const [k, v] of Object.entries(en)) if (k !== v && catalog[k] !== undefined && !VARIANT.test(k)) put(v, catalog[k]);
  // 2b. tvOS-only copy (tools/locales-tvos.json); a translation must keep the key's placeholders.
  let tv = 0;
  for (const [k, byLang] of Object.entries(extras)) {
    const v = byLang[code];
    const names = new Set([...k.matchAll(PLACEHOLDER)].map((m) => m[1]));
    const bad = typeof v !== "string" || [...v.matchAll(PLACEHOLDER)].some((m) => !names.has(m[1]));
    if (bad) { console.warn(`locales-tvos.json: ${code} ${v === undefined ? "missing" : "bad placeholder"} for ${JSON.stringify(k)}`); continue; }
    if (!entries.has(k)) tv++;
    put(k, v);
  }
  // 3. Swift-format twins of {placeholder} keys, and the plural table.
  const plurals = [];
  for (const [k, v] of [...entries]) {
    if (!k.includes("{")) continue;
    for (const [sk, sv] of swiftForms(k, v)) put(sk, sv);
    const one = catalog[`${k}#one`], few = catalog[`${k}#few`];
    const names = [...k.matchAll(PLACEHOLDER)];
    if ((one !== undefined || few !== undefined) && names.length === 1) {
      const ok = [one, few].every((f) => f === undefined || [...f.matchAll(PLACEHOLDER)].every((m) => m[1] === names[0][1]));
      if (ok) plurals.push({ key: k, forms: { one, few, many: v } });
    }
  }
  const dir = path.join(outDir, `${code}.lproj`);
  fs.mkdirSync(dir);
  const strings = stringsFile(entries);
  fs.writeFileSync(path.join(dir, "Localizable.strings"), strings);
  if (plurals.length) fs.writeFileSync(path.join(dir, "Localizable.stringsdict"), stringsdictFile(plurals));
  // The engine gets upstream's catalog untouched, variants included (translate.ts resolve()).
  const json = JSON.stringify(catalog);
  fs.writeFileSync(path.join(outDir, `${code}.json`), json);
  const bytes = Buffer.byteLength(strings) + Buffer.byteLength(json);
  total += bytes;
  summary.push(`${code} ${entries.size} keys (${tv} tvOS), ${plurals.length} plurals, ${(bytes / 1048576).toFixed(1)} MB`);
}
console.log(summary.join("\n"));
console.log(`App/Locales  ${(total / 1048576).toFixed(1)} MB for ${summary.length} languages`);
